package main

type Cube struct {
	x          float32
	y          float32
	z          float32
	xAngle     int
	yAngle     int
	zAngle     int
	frontColor int
	backColor  int
	leftColor  int
	rightColor int
	upColor    int
	downColor  int
}

// CubeDescriptors initial position is always correct: front-green, back-blue, left-orange, right-redKey, top-yellow, bottom-white
var CubeDescriptors = []Cube{
	//1-1
	{
		x:          -1,
		y:          1,
		z:          1,
		frontColor: greenKey,
		backColor:  blackKey,
		leftColor:  orangeKey,
		rightColor: blackKey,
		upColor:    yellowKey,
		downColor:  blackKey,
	},
	{
		x:          0,
		y:          1,
		z:          1,
		frontColor: greenKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: blackKey,
		upColor:    yellowKey,
		downColor:  blackKey,
	},
	{
		x:          1,
		y:          1,
		z:          1,
		frontColor: greenKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: redKey,
		upColor:    yellowKey,
		downColor:  blackKey,
	},
	//1-2
	{
		x:          -1,
		y:          0,
		z:          1,
		frontColor: greenKey,
		backColor:  blackKey,
		leftColor:  orangeKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  blackKey,
	},
	{
		x:          0,
		y:          0,
		z:          1,
		frontColor: greenKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  blackKey,
	},
	{
		x:          1,
		y:          0,
		z:          1,
		frontColor: greenKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: redKey,
		upColor:    blackKey,
		downColor:  blackKey,
	},
	//1-3
	{
		x:          -1,
		y:          -1,
		z:          1,
		frontColor: greenKey,
		backColor:  blackKey,
		leftColor:  orangeKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  whiteKey,
	},
	{
		x:          0,
		y:          -1,
		z:          1,
		frontColor: greenKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  whiteKey,
	},
	{
		x:          1,
		y:          -1,
		z:          1,
		frontColor: greenKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: redKey,
		upColor:    blackKey,
		downColor:  whiteKey,
	},
	/**********************************************************************************************/
	/**********************************************************************************************/
	/**********************************************************************************************/
	//2-1
	{
		x:          -1,
		y:          1,
		z:          0,
		frontColor: blackKey,
		backColor:  blackKey,
		leftColor:  orangeKey,
		rightColor: blackKey,
		upColor:    yellowKey,
		downColor:  blackKey,
	},
	{
		x:          0,
		y:          1,
		z:          0,
		frontColor: blackKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: blackKey,
		upColor:    yellowKey,
		downColor:  blackKey,
	},
	{
		x:          1,
		y:          1,
		z:          0,
		frontColor: blackKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: redKey,
		upColor:    yellowKey,
		downColor:  blackKey,
	},
	//2-2
	{
		x:          -1,
		y:          0,
		z:          0,
		frontColor: blackKey,
		backColor:  blackKey,
		leftColor:  orangeKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  blackKey,
	},
	{
		x:          0,
		y:          0,
		z:          0,
		frontColor: blackKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  blackKey,
	},
	{
		x:          1,
		y:          0,
		z:          0,
		frontColor: blackKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: redKey,
		upColor:    blackKey,
		downColor:  blackKey,
	},
	//2-3
	{
		x:          -1,
		y:          -1,
		z:          0,
		frontColor: blackKey,
		backColor:  blackKey,
		leftColor:  orangeKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  whiteKey,
	},
	{
		x:          0,
		y:          -1,
		z:          0,
		frontColor: blackKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  whiteKey,
	},
	{
		x:          1,
		y:          -1,
		z:          0,
		frontColor: blackKey,
		backColor:  blackKey,
		leftColor:  blackKey,
		rightColor: redKey,
		upColor:    blackKey,
		downColor:  whiteKey,
	},
	/**********************************************************************************************/
	/**********************************************************************************************/
	/**********************************************************************************************/
	//3-1
	{
		x:          -1,
		y:          1,
		z:          -1,
		frontColor: blackKey,
		backColor:  blueKey,
		leftColor:  orangeKey,
		rightColor: blackKey,
		upColor:    yellowKey,
		downColor:  blackKey,
	},
	{
		x:          0,
		y:          1,
		z:          -1,
		frontColor: blackKey,
		backColor:  blueKey,
		leftColor:  blackKey,
		rightColor: blackKey,
		upColor:    yellowKey,
		downColor:  blackKey,
	},
	{
		x:          1,
		y:          1,
		z:          -1,
		frontColor: blackKey,
		backColor:  blueKey,
		leftColor:  blackKey,
		rightColor: redKey,
		upColor:    yellowKey,
		downColor:  blackKey,
	},
	//3-2
	{
		x:          -1,
		y:          0,
		z:          -1,
		frontColor: blackKey,
		backColor:  blueKey,
		leftColor:  orangeKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  blackKey,
	},
	{
		x:          0,
		y:          0,
		z:          -1,
		frontColor: blackKey,
		backColor:  blueKey,
		leftColor:  blackKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  blackKey,
	},
	{
		x:          1,
		y:          0,
		z:          -1,
		frontColor: blackKey,
		backColor:  blueKey,
		leftColor:  blackKey,
		rightColor: redKey,
		upColor:    blackKey,
		downColor:  blackKey,
	},
	//3-3
	{
		x:          -1,
		y:          -1,
		z:          -1,
		frontColor: blackKey,
		backColor:  blueKey,
		leftColor:  orangeKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  whiteKey,
	},
	{
		x:          0,
		y:          -1,
		z:          -1,
		frontColor: blackKey,
		backColor:  blueKey,
		leftColor:  blackKey,
		rightColor: blackKey,
		upColor:    blackKey,
		downColor:  whiteKey,
	},
	{
		x:          1,
		y:          -1,
		z:          -1,
		frontColor: blackKey,
		backColor:  blueKey,
		leftColor:  blackKey,
		rightColor: redKey,
		upColor:    blackKey,
		downColor:  whiteKey,
	},
}
