package main

import rl "github.com/gen2brain/raylib-go/raylib"

type Cube struct {
	x          float32
	y          float32
	z          float32
	xAngle     int
	yAngle     int
	zAngle     int
	frontColor rl.Color
	backColor  rl.Color
	leftColor  rl.Color
	rightColor rl.Color
	upColor    rl.Color
	downColor  rl.Color
}

// CubeDescriptors initial position is always correct: front-green, back-blue, left-orange, right-red, top-yellow, bottom-white
var CubeDescriptors = []Cube{
	//1-1
	{
		x:          -1,
		y:          1,
		z:          1,
		frontColor: green,
		backColor:  black,
		leftColor:  orange,
		rightColor: black,
		upColor:    yellow,
		downColor:  black,
	},
	{
		x:          0,
		y:          1,
		z:          1,
		frontColor: green,
		backColor:  black,
		leftColor:  black,
		rightColor: black,
		upColor:    yellow,
		downColor:  black,
	},
	{
		x:          1,
		y:          1,
		z:          1,
		frontColor: green,
		backColor:  black,
		leftColor:  black,
		rightColor: red,
		upColor:    yellow,
		downColor:  black,
	},
	//1-2
	{
		x:          -1,
		y:          0,
		z:          1,
		frontColor: green,
		backColor:  black,
		leftColor:  orange,
		rightColor: black,
		upColor:    black,
		downColor:  black,
	},
	{
		x:          0,
		y:          0,
		z:          1,
		frontColor: green,
		backColor:  black,
		leftColor:  black,
		rightColor: black,
		upColor:    black,
		downColor:  black,
	},
	{
		x:          1,
		y:          0,
		z:          1,
		frontColor: green,
		backColor:  black,
		leftColor:  black,
		rightColor: red,
		upColor:    black,
		downColor:  black,
	},
	//1-3
	{
		x:          -1,
		y:          -1,
		z:          1,
		frontColor: green,
		backColor:  black,
		leftColor:  orange,
		rightColor: black,
		upColor:    black,
		downColor:  white,
	},
	{
		x:          0,
		y:          -1,
		z:          1,
		frontColor: green,
		backColor:  black,
		leftColor:  black,
		rightColor: black,
		upColor:    black,
		downColor:  white,
	},
	{
		x:          1,
		y:          -1,
		z:          1,
		frontColor: green,
		backColor:  black,
		leftColor:  black,
		rightColor: red,
		upColor:    black,
		downColor:  white,
	},
	/**********************************************************************************************/
	/**********************************************************************************************/
	/**********************************************************************************************/
	//2-1
	{
		x:          -1,
		y:          1,
		z:          0,
		frontColor: black,
		backColor:  black,
		leftColor:  orange,
		rightColor: black,
		upColor:    yellow,
		downColor:  black,
	},
	{
		x:          0,
		y:          1,
		z:          0,
		frontColor: black,
		backColor:  black,
		leftColor:  black,
		rightColor: black,
		upColor:    yellow,
		downColor:  black,
	},
	{
		x:          1,
		y:          1,
		z:          0,
		frontColor: black,
		backColor:  black,
		leftColor:  black,
		rightColor: red,
		upColor:    yellow,
		downColor:  black,
	},
	//2-2
	{
		x:          -1,
		y:          0,
		z:          0,
		frontColor: black,
		backColor:  black,
		leftColor:  orange,
		rightColor: black,
		upColor:    black,
		downColor:  black,
	},
	{
		x:          0,
		y:          0,
		z:          0,
		frontColor: black,
		backColor:  black,
		leftColor:  black,
		rightColor: black,
		upColor:    black,
		downColor:  black,
	},
	{
		x:          1,
		y:          0,
		z:          0,
		frontColor: black,
		backColor:  black,
		leftColor:  black,
		rightColor: red,
		upColor:    black,
		downColor:  black,
	},
	//2-3
	{
		x:          -1,
		y:          -1,
		z:          0,
		frontColor: black,
		backColor:  black,
		leftColor:  orange,
		rightColor: black,
		upColor:    black,
		downColor:  white,
	},
	{
		x:          0,
		y:          -1,
		z:          0,
		frontColor: black,
		backColor:  black,
		leftColor:  black,
		rightColor: black,
		upColor:    black,
		downColor:  white,
	},
	{
		x:          1,
		y:          -1,
		z:          0,
		frontColor: black,
		backColor:  black,
		leftColor:  black,
		rightColor: red,
		upColor:    black,
		downColor:  white,
	},
	/**********************************************************************************************/
	/**********************************************************************************************/
	/**********************************************************************************************/
	//3-1
	{
		x:          -1,
		y:          1,
		z:          -1,
		frontColor: black,
		backColor:  blue,
		leftColor:  orange,
		rightColor: black,
		upColor:    yellow,
		downColor:  black,
	},
	{
		x:          0,
		y:          1,
		z:          -1,
		frontColor: black,
		backColor:  blue,
		leftColor:  black,
		rightColor: black,
		upColor:    yellow,
		downColor:  black,
	},
	{
		x:          1,
		y:          1,
		z:          -1,
		frontColor: black,
		backColor:  blue,
		leftColor:  black,
		rightColor: red,
		upColor:    yellow,
		downColor:  black,
	},
	//3-2
	{
		x:          -1,
		y:          0,
		z:          -1,
		frontColor: black,
		backColor:  blue,
		leftColor:  orange,
		rightColor: black,
		upColor:    black,
		downColor:  black,
	},
	{
		x:          0,
		y:          0,
		z:          -1,
		frontColor: black,
		backColor:  blue,
		leftColor:  black,
		rightColor: black,
		upColor:    black,
		downColor:  black,
	},
	{
		x:          1,
		y:          0,
		z:          -1,
		frontColor: black,
		backColor:  blue,
		leftColor:  black,
		rightColor: red,
		upColor:    black,
		downColor:  black,
	},
	//3-3
	{
		x:          -1,
		y:          -1,
		z:          -1,
		frontColor: black,
		backColor:  blue,
		leftColor:  orange,
		rightColor: black,
		upColor:    black,
		downColor:  white,
	},
	{
		x:          0,
		y:          -1,
		z:          -1,
		frontColor: black,
		backColor:  blue,
		leftColor:  black,
		rightColor: black,
		upColor:    black,
		downColor:  white,
	},
	{
		x:          1,
		y:          -1,
		z:          -1,
		frontColor: black,
		backColor:  blue,
		leftColor:  black,
		rightColor: red,
		upColor:    black,
		downColor:  white,
	},
}
