package main

type Cube struct {
	x          float32
	y          float32
	z          float32
	xAngle     int
	yAngle     int
	zAngle     int
	frontColor int
	backColor  int
	leftColor  int
	rightColor int
	upColor    int
	downColor  int
}

// CubeDescriptors initial position is always correct: front-green, back-blue, left-orange, right-red, top-yellow, bottom-white
var CubeDescriptors = []Cube{
	//1-1
	{
		x:          -1,
		y:          1,
		z:          1,
		frontColor: G,
		backColor:  BL,
		leftColor:  O,
		rightColor: BL,
		upColor:    Y,
		downColor:  BL,
	},
	{
		x:          0,
		y:          1,
		z:          1,
		frontColor: G,
		backColor:  BL,
		leftColor:  BL,
		rightColor: BL,
		upColor:    Y,
		downColor:  BL,
	},
	{
		x:          1,
		y:          1,
		z:          1,
		frontColor: G,
		backColor:  BL,
		leftColor:  BL,
		rightColor: R,
		upColor:    Y,
		downColor:  BL,
	},
	//1-2
	{
		x:          -1,
		y:          0,
		z:          1,
		frontColor: G,
		backColor:  BL,
		leftColor:  O,
		rightColor: BL,
		upColor:    BL,
		downColor:  BL,
	},
	{
		x:          0,
		y:          0,
		z:          1,
		frontColor: G,
		backColor:  BL,
		leftColor:  BL,
		rightColor: BL,
		upColor:    BL,
		downColor:  BL,
	},
	{
		x:          1,
		y:          0,
		z:          1,
		frontColor: G,
		backColor:  BL,
		leftColor:  BL,
		rightColor: R,
		upColor:    BL,
		downColor:  BL,
	},
	//1-3
	{
		x:          -1,
		y:          -1,
		z:          1,
		frontColor: G,
		backColor:  BL,
		leftColor:  O,
		rightColor: BL,
		upColor:    BL,
		downColor:  W,
	},
	{
		x:          0,
		y:          -1,
		z:          1,
		frontColor: G,
		backColor:  BL,
		leftColor:  BL,
		rightColor: BL,
		upColor:    BL,
		downColor:  W,
	},
	{
		x:          1,
		y:          -1,
		z:          1,
		frontColor: G,
		backColor:  BL,
		leftColor:  BL,
		rightColor: R,
		upColor:    BL,
		downColor:  W,
	},
	/**********************************************************************************************/
	/**********************************************************************************************/
	/**********************************************************************************************/
	//2-1
	{
		x:          -1,
		y:          1,
		z:          0,
		frontColor: BL,
		backColor:  BL,
		leftColor:  O,
		rightColor: BL,
		upColor:    Y,
		downColor:  BL,
	},
	{
		x:          0,
		y:          1,
		z:          0,
		frontColor: BL,
		backColor:  BL,
		leftColor:  BL,
		rightColor: BL,
		upColor:    Y,
		downColor:  BL,
	},
	{
		x:          1,
		y:          1,
		z:          0,
		frontColor: BL,
		backColor:  BL,
		leftColor:  BL,
		rightColor: R,
		upColor:    Y,
		downColor:  BL,
	},
	//2-2
	{
		x:          -1,
		y:          0,
		z:          0,
		frontColor: BL,
		backColor:  BL,
		leftColor:  O,
		rightColor: BL,
		upColor:    BL,
		downColor:  BL,
	},
	{
		x:          0,
		y:          0,
		z:          0,
		frontColor: BL,
		backColor:  BL,
		leftColor:  BL,
		rightColor: BL,
		upColor:    BL,
		downColor:  BL,
	},
	{
		x:          1,
		y:          0,
		z:          0,
		frontColor: BL,
		backColor:  BL,
		leftColor:  BL,
		rightColor: R,
		upColor:    BL,
		downColor:  BL,
	},
	//2-3
	{
		x:          -1,
		y:          -1,
		z:          0,
		frontColor: BL,
		backColor:  BL,
		leftColor:  O,
		rightColor: BL,
		upColor:    BL,
		downColor:  W,
	},
	{
		x:          0,
		y:          -1,
		z:          0,
		frontColor: BL,
		backColor:  BL,
		leftColor:  BL,
		rightColor: BL,
		upColor:    BL,
		downColor:  W,
	},
	{
		x:          1,
		y:          -1,
		z:          0,
		frontColor: BL,
		backColor:  BL,
		leftColor:  BL,
		rightColor: R,
		upColor:    BL,
		downColor:  W,
	},
	/**********************************************************************************************/
	/**********************************************************************************************/
	/**********************************************************************************************/
	//3-1
	{
		x:          -1,
		y:          1,
		z:          -1,
		frontColor: BL,
		backColor:  B,
		leftColor:  O,
		rightColor: BL,
		upColor:    Y,
		downColor:  BL,
	},
	{
		x:          0,
		y:          1,
		z:          -1,
		frontColor: BL,
		backColor:  B,
		leftColor:  BL,
		rightColor: BL,
		upColor:    Y,
		downColor:  BL,
	},
	{
		x:          1,
		y:          1,
		z:          -1,
		frontColor: BL,
		backColor:  B,
		leftColor:  BL,
		rightColor: R,
		upColor:    Y,
		downColor:  BL,
	},
	//3-2
	{
		x:          -1,
		y:          0,
		z:          -1,
		frontColor: BL,
		backColor:  B,
		leftColor:  O,
		rightColor: BL,
		upColor:    BL,
		downColor:  BL,
	},
	{
		x:          0,
		y:          0,
		z:          -1,
		frontColor: BL,
		backColor:  B,
		leftColor:  BL,
		rightColor: BL,
		upColor:    BL,
		downColor:  BL,
	},
	{
		x:          1,
		y:          0,
		z:          -1,
		frontColor: BL,
		backColor:  B,
		leftColor:  BL,
		rightColor: R,
		upColor:    BL,
		downColor:  BL,
	},
	//3-3
	{
		x:          -1,
		y:          -1,
		z:          -1,
		frontColor: BL,
		backColor:  B,
		leftColor:  O,
		rightColor: BL,
		upColor:    BL,
		downColor:  W,
	},
	{
		x:          0,
		y:          -1,
		z:          -1,
		frontColor: BL,
		backColor:  B,
		leftColor:  BL,
		rightColor: BL,
		upColor:    BL,
		downColor:  W,
	},
	{
		x:          1,
		y:          -1,
		z:          -1,
		frontColor: BL,
		backColor:  B,
		leftColor:  BL,
		rightColor: R,
		upColor:    BL,
		downColor:  W,
	},
}
